-- name: CurrentWeatherByAddressIDAndBaseUnit :one
SELECT *
FROM current_weather
WHERE address_id = ?
  AND base_unit = ?;

-- name: UpdateCurrentWeather :exec
INSERT INTO current_weather (address_id,
                             timestamp,
                             temperature,
                             apparent_temperature,
                             weather_code,
                             wind_speed,
                             wind_gusts,
                             wind_direction,
                             relative_humidity,
                             pressure_msl,
                             temp_day_min,
                             temp_day_max,
                             uv_index,
                             is_day,
                             sunrise_utc,
                             sunset_utc,
                             condition,
                             category,
                             icon,
                             winddir_icon,
                             winddir_text,
                             temp_unit,
                             windspeed_unit,
                             humidity_unit,
                             pressure_unit,
                             winddir_unit,
                             timezone,
                             timezone_abbr,
                             base_unit,
                             updated_at)
VALUES (:address_id,
        :timestamp,
        :temperature,
        :apparent_temperature,
        :weather_code,
        :wind_speed,
        :wind_gusts,
        :wind_direction,
        :relative_humidity,
        :pressure_msl,
        :temp_day_min,
        :temp_day_max,
        :uv_index,
        :is_day,
        :sunrise_utc,
        :sunset_utc,
        :condition,
        :category,
        :icon,
        :winddir_icon,
        :winddir_text,
        :temp_unit,
        :windspeed_unit,
        :humidity_unit,
        :pressure_unit,
        :winddir_unit,
        :timezone,
        :timezone_abbr,
        :base_unit,
        :updated_at)
ON CONFLICT (address_id, base_unit) DO UPDATE SET timestamp            = excluded.timestamp,
                                                  temperature          = excluded.temperature,
                                                  apparent_temperature = excluded.apparent_temperature,
                                                  weather_code         = excluded.weather_code,
                                                  wind_speed           = excluded.wind_speed,
                                                  wind_gusts           = excluded.wind_gusts,
                                                  wind_direction       = excluded.wind_direction,
                                                  relative_humidity    = excluded.relative_humidity,
                                                  pressure_msl         = excluded.pressure_msl,
                                                  temp_day_min         = excluded.temp_day_min,
                                                  temp_day_max         = excluded.temp_day_max,
                                                  uv_index             = excluded.uv_index,
                                                  is_day               = excluded.is_day,
                                                  sunrise_utc          = excluded.sunrise_utc,
                                                  sunset_utc           = excluded.sunset_utc,
                                                  condition            = excluded.condition,
                                                  category             = excluded.category,
                                                  icon                 = excluded.icon,
                                                  winddir_icon         = excluded.winddir_icon,
                                                  winddir_text         = excluded.winddir_text,
                                                  temp_unit            = excluded.temp_unit,
                                                  windspeed_unit       = excluded.windspeed_unit,
                                                  humidity_unit        = excluded.humidity_unit,
                                                  pressure_unit        = excluded.pressure_unit,
                                                  winddir_unit         = excluded.winddir_unit,
                                                  timezone             = excluded.timezone,
                                                  timezone_abbr        = excluded.timezone_abbr,
                                                  base_unit            = excluded.base_unit,
                                                  updated_at           = excluded.updated_at
WHERE excluded.timestamp > current_weather.timestamp;

