-- name: CurrentWeatherByAddressID :one
SELECT *
FROM current_weather
WHERE address_id = ?;

/*
address_id           INTEGER NOT NULL REFERENCES addresses (id) ON DELETE CASCADE,
    timestamp            INTEGER,
    temperature          REAL,
    apparent_temperature REAL,
    weather_code         INTEGER,
    wind_speed           REAL,
    wind_gusts           REAL,
    wind_direction       REAL,
    relative_humidity    REAL,
    pressure_msl         REAL,
    humidity             REAL,
    is_day               BOOLEAN,
    condition            TEXT    NOT NULL,
    category             TEXT    NOT NULL,
    icon                 TEXT    NOT NULL,
    winddir_icon         TEXT    NOT NULL,
    winddir_text         TEXT    NOT NULL,
    temp_unit            TEXT,
    windspeed_unit       TEXT,
    humidity_unit        TEXT,
    pressure_unit        TEXT,
    winddir_unit         TEXT,
    updated_at           INTEGER NOT NULL

 */

-- name: UpdateCurrentWeather :exec
INSERT INTO current_weather (address_id,
                             timestamp,
                             temperature,
                             apparent_temperature,
                             weather_code,
                             wind_speed,
                             wind_gusts,
                             wind_direction,
                             relative_humidity,
                             pressure_msl,
                             is_day,
                             condition,
                             category,
                             icon,
                             winddir_icon,
                             winddir_text,
                             temp_unit,
                             windspeed_unit,
                             humidity_unit,
                             pressure_unit,
                             winddir_unit,
                             updated_at)
VALUES (:address_id,
        :timestamp,
        :temperature,
        :apparent_temperature,
        :weather_code,
        :wind_speed,
        :wind_gusts,
        :wind_direction,
        :relative_humidity,
        :pressure_msl,
        :is_day,
        :condition,
        :category,
        :icon,
        :winddir_icon,
        :winddir_text,
        :temp_unit,
        :windspeed_unit,
        :humidity_unit,
        :pressure_unit,
        :winddir_unit,
        :updated_at)
ON CONFLICT (address_id) DO UPDATE SET timestamp            = excluded.timestamp,
                                       temperature          = excluded.temperature,
                                       apparent_temperature = excluded.apparent_temperature,
                                       weather_code         = excluded.weather_code,
                                       wind_speed           = excluded.wind_speed,
                                       wind_gusts           = excluded.wind_gusts,
                                       wind_direction       = excluded.wind_direction,
                                       relative_humidity    = excluded.relative_humidity,
                                       pressure_msl         = excluded.pressure_msl,
                                       is_day               = excluded.is_day,
                                       condition            = excluded.condition,
                                       category             = excluded.category,
                                       icon                 = excluded.icon,
                                       winddir_icon         = excluded.winddir_icon,
                                       winddir_text         = excluded.winddir_text,
                                       temp_unit            = excluded.temp_unit,
                                       windspeed_unit       = excluded.windspeed_unit,
                                       humidity_unit        = excluded.humidity_unit,
                                       pressure_unit        = excluded.pressure_unit,
                                       winddir_unit         = excluded.winddir_unit,
                                       updated_at           = excluded.updated_at
WHERE excluded.timestamp > current_weather.timestamp;

