# SPDX-FileCopyrightText: Winni Neessen <wn@neessen.dev>
#
# SPDX-License-Identifier: MIT

[project]
name = "localweather"
revision = "1.0"

[profiles.default]
LOCALWEATHER_GEOCODER_APIKEY = { description = "Optional API key for geocoding provider", required = false }

