// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addresses.sql

package model

import (
	"context"
	"database/sql"
)

const addressByCoords = `-- name: AddressByCoords :one
SELECT id, latitude, longitude, lat_trunc, lon_trunc, altitude, accuracy, display_name, country, state, municipality, city_district, postcode, city, suburb, street, house_number, provider, locale, created_at
FROM addresses
WHERE lat_trunc = ?
  AND lon_trunc = ?
  AND locale = ?
`

type AddressByCoordsParams struct {
	LatTrunc float64
	LonTrunc float64
	Locale   string
}

func (q *Queries) AddressByCoords(ctx context.Context, arg AddressByCoordsParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, addressByCoords, arg.LatTrunc, arg.LonTrunc, arg.Locale)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Latitude,
		&i.Longitude,
		&i.LatTrunc,
		&i.LonTrunc,
		&i.Altitude,
		&i.Accuracy,
		&i.DisplayName,
		&i.Country,
		&i.State,
		&i.Municipality,
		&i.CityDistrict,
		&i.Postcode,
		&i.City,
		&i.Suburb,
		&i.Street,
		&i.HouseNumber,
		&i.Provider,
		&i.Locale,
		&i.CreatedAt,
	)
	return i, err
}

const clearCurrentAddress = `-- name: ClearCurrentAddress :exec
DELETE
FROM current_address
`

func (q *Queries) ClearCurrentAddress(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearCurrentAddress)
	return err
}

const currentAddress = `-- name: CurrentAddress :one
SELECT lock, address_id, updated_at, current_address.created_at, id, latitude, longitude, lat_trunc, lon_trunc, altitude, accuracy, display_name, country, state, municipality, city_district, postcode, city, suburb, street, house_number, provider, locale, addresses.created_at
FROM current_address
         JOIN addresses ON addresses.id = current_address.address_id
LIMIT 1
`

type CurrentAddressRow struct {
	Lock         int64
	AddressID    int64
	UpdatedAt    int64
	CreatedAt    int64
	ID           int64
	Latitude     float64
	Longitude    float64
	LatTrunc     float64
	LonTrunc     float64
	Altitude     sql.NullFloat64
	Accuracy     float64
	DisplayName  string
	Country      sql.NullString
	State        sql.NullString
	Municipality sql.NullString
	CityDistrict sql.NullString
	Postcode     sql.NullString
	City         sql.NullString
	Suburb       sql.NullString
	Street       sql.NullString
	HouseNumber  sql.NullString
	Provider     string
	Locale       string
	CreatedAt_2  int64
}

func (q *Queries) CurrentAddress(ctx context.Context) (CurrentAddressRow, error) {
	row := q.db.QueryRowContext(ctx, currentAddress)
	var i CurrentAddressRow
	err := row.Scan(
		&i.Lock,
		&i.AddressID,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.ID,
		&i.Latitude,
		&i.Longitude,
		&i.LatTrunc,
		&i.LonTrunc,
		&i.Altitude,
		&i.Accuracy,
		&i.DisplayName,
		&i.Country,
		&i.State,
		&i.Municipality,
		&i.CityDistrict,
		&i.Postcode,
		&i.City,
		&i.Suburb,
		&i.Street,
		&i.HouseNumber,
		&i.Provider,
		&i.Locale,
		&i.CreatedAt_2,
	)
	return i, err
}

const newAddress = `-- name: NewAddress :one
INSERT INTO addresses
(latitude, longitude, lat_trunc, lon_trunc, altitude, accuracy, display_name, country, state, municipality,
 city_district, postcode, city,
 suburb, street, house_number, provider, locale, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, latitude, longitude, lat_trunc, lon_trunc, altitude, accuracy, display_name, country, state, municipality, city_district, postcode, city, suburb, street, house_number, provider, locale, created_at
`

type NewAddressParams struct {
	Latitude     float64
	Longitude    float64
	LatTrunc     float64
	LonTrunc     float64
	Altitude     sql.NullFloat64
	Accuracy     float64
	DisplayName  string
	Country      sql.NullString
	State        sql.NullString
	Municipality sql.NullString
	CityDistrict sql.NullString
	Postcode     sql.NullString
	City         sql.NullString
	Suburb       sql.NullString
	Street       sql.NullString
	HouseNumber  sql.NullString
	Provider     string
	Locale       string
	CreatedAt    int64
}

func (q *Queries) NewAddress(ctx context.Context, arg NewAddressParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, newAddress,
		arg.Latitude,
		arg.Longitude,
		arg.LatTrunc,
		arg.LonTrunc,
		arg.Altitude,
		arg.Accuracy,
		arg.DisplayName,
		arg.Country,
		arg.State,
		arg.Municipality,
		arg.CityDistrict,
		arg.Postcode,
		arg.City,
		arg.Suburb,
		arg.Street,
		arg.HouseNumber,
		arg.Provider,
		arg.Locale,
		arg.CreatedAt,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Latitude,
		&i.Longitude,
		&i.LatTrunc,
		&i.LonTrunc,
		&i.Altitude,
		&i.Accuracy,
		&i.DisplayName,
		&i.Country,
		&i.State,
		&i.Municipality,
		&i.CityDistrict,
		&i.Postcode,
		&i.City,
		&i.Suburb,
		&i.Street,
		&i.HouseNumber,
		&i.Provider,
		&i.Locale,
		&i.CreatedAt,
	)
	return i, err
}

const updateCurrentAddress = `-- name: UpdateCurrentAddress :exec
INSERT INTO current_address (address_id, created_at, updated_at)
VALUES (?, ?, ?)
ON CONFLICT (lock) DO UPDATE SET
                                 address_id = excluded.address_id,
                                 updated_at = excluded.updated_at
`

type UpdateCurrentAddressParams struct {
	AddressID int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) UpdateCurrentAddress(ctx context.Context, arg UpdateCurrentAddressParams) error {
	_, err := q.db.ExecContext(ctx, updateCurrentAddress, arg.AddressID, arg.CreatedAt, arg.UpdatedAt)
	return err
}
