// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addresses.sql

package model

import (
	"context"
)

const addressByCoords = `-- name: AddressByCoords :one
SELECT id, latitude, longitude, altitude, accuracy, display_name, country, state, municipality, city_district, postcode, city, suburb, street, house_number, created_at
FROM addresses
WHERE latitude = ? AND longitude = ?
`

type AddressByCoordsParams struct {
	Latitude  interface{} `json:"latitude"`
	Longitude interface{} `json:"longitude"`
}

func (q *Queries) AddressByCoords(ctx context.Context, arg AddressByCoordsParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, addressByCoords, arg.Latitude, arg.Longitude)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.Accuracy,
		&i.DisplayName,
		&i.Country,
		&i.State,
		&i.Municipality,
		&i.CityDistrict,
		&i.Postcode,
		&i.City,
		&i.Suburb,
		&i.Street,
		&i.HouseNumber,
		&i.CreatedAt,
	)
	return i, err
}

const newAddress = `-- name: NewAddress :one
INSERT INTO addresses
(latitude, longitude, altitude, accuracy, display_name, country, state, municipality, city_district, postcode, city, suburb, street, house_number)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, latitude, longitude, altitude, accuracy, display_name, country, state, municipality, city_district, postcode, city, suburb, street, house_number, created_at
`

type NewAddressParams struct {
	Latitude     interface{} `json:"latitude"`
	Longitude    interface{} `json:"longitude"`
	Altitude     interface{} `json:"altitude"`
	Accuracy     interface{} `json:"accuracy"`
	DisplayName  interface{} `json:"display_name"`
	Country      interface{} `json:"country"`
	State        interface{} `json:"state"`
	Municipality interface{} `json:"municipality"`
	CityDistrict interface{} `json:"city_district"`
	Postcode     interface{} `json:"postcode"`
	City         interface{} `json:"city"`
	Suburb       interface{} `json:"suburb"`
	Street       interface{} `json:"street"`
	HouseNumber  interface{} `json:"house_number"`
}

func (q *Queries) NewAddress(ctx context.Context, arg NewAddressParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, newAddress,
		arg.Latitude,
		arg.Longitude,
		arg.Altitude,
		arg.Accuracy,
		arg.DisplayName,
		arg.Country,
		arg.State,
		arg.Municipality,
		arg.CityDistrict,
		arg.Postcode,
		arg.City,
		arg.Suburb,
		arg.Street,
		arg.HouseNumber,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.Accuracy,
		&i.DisplayName,
		&i.Country,
		&i.State,
		&i.Municipality,
		&i.CityDistrict,
		&i.Postcode,
		&i.City,
		&i.Suburb,
		&i.Street,
		&i.HouseNumber,
		&i.CreatedAt,
	)
	return i, err
}
