// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package model

import (
	"context"
)

const locationByID = `-- name: LocationByID :one
SELECT id, name, latitude, longitude, altitude, accuracy, updated_at, created_at
FROM locations
WHERE id = ?
`

func (q *Queries) LocationByID(ctx context.Context, id int64) (Location, error) {
	row := q.db.QueryRowContext(ctx, locationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.Accuracy,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
