// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package model

import (
	"database/sql"
)

type Address struct {
	ID           int64
	Latitude     float64
	Longitude    float64
	LatTrunc     float64
	LonTrunc     float64
	Altitude     sql.NullFloat64
	Accuracy     float64
	DisplayName  string
	Country      sql.NullString
	State        sql.NullString
	Municipality sql.NullString
	CityDistrict sql.NullString
	Postcode     sql.NullString
	City         sql.NullString
	Suburb       sql.NullString
	Street       sql.NullString
	HouseNumber  sql.NullString
	Provider     string
	Locale       string
	CreatedAt    int64
}

type CurrentAddress struct {
	Lock      int64
	AddressID int64
	UpdatedAt int64
	CreatedAt int64
}

type CurrentWeather struct {
	AddressID           int64
	Timestamp           int64
	Temperature         float64
	ApparentTemperature float64
	WeatherCode         int64
	WindSpeed           float64
	WindGusts           float64
	WindDirection       float64
	RelativeHumidity    float64
	PressureMsl         float64
	IsDay               bool
	UpdatedAt           int64
}
