// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package model

import (
	"database/sql"
)

type Address struct {
	ID           int64           `json:"id"`
	Latitude     float64         `json:"latitude"`
	Longitude    float64         `json:"longitude"`
	LatTrunc     float64         `json:"lat_trunc"`
	LonTrunc     float64         `json:"lon_trunc"`
	Altitude     sql.NullFloat64 `json:"altitude"`
	Accuracy     float64         `json:"accuracy"`
	DisplayName  string          `json:"display_name"`
	Country      sql.NullString  `json:"country"`
	State        sql.NullString  `json:"state"`
	Municipality sql.NullString  `json:"municipality"`
	CityDistrict sql.NullString  `json:"city_district"`
	Postcode     sql.NullString  `json:"postcode"`
	City         sql.NullString  `json:"city"`
	Suburb       sql.NullString  `json:"suburb"`
	Street       sql.NullString  `json:"street"`
	HouseNumber  sql.NullString  `json:"house_number"`
	Provider     string          `json:"provider"`
	Locale       string          `json:"locale"`
	CreatedAt    int64           `json:"created_at"`
}

type CurrentAddress struct {
	Lock      int64 `json:"lock"`
	AddressID int64 `json:"address_id"`
	UpdatedAt int64 `json:"updated_at"`
	CreatedAt int64 `json:"created_at"`
}

type CurrentWeather struct {
	AddressID           int64           `json:"-"`
	Timestamp           sql.NullInt64   `json:"timestamp_unix"`
	Temperature         sql.NullFloat64 `json:"temperature"`
	ApparentTemperature sql.NullFloat64 `json:"apparent_temperature"`
	WeatherCode         sql.NullInt64   `json:"weather_code"`
	WindSpeed           sql.NullFloat64 `json:"wind_speed"`
	WindGusts           sql.NullFloat64 `json:"wind_gusts"`
	WindDirection       sql.NullFloat64 `json:"wind_direction"`
	RelativeHumidity    sql.NullFloat64 `json:"relative_humidity"`
	PressureMsl         sql.NullFloat64 `json:"pressure_msl"`
	TempDayMin          sql.NullFloat64 `json:"temp_day_min"`
	TempDayMax          sql.NullFloat64 `json:"temp_day_max"`
	UvIndex             sql.NullFloat64 `json:"uv_index"`
	IsDay               sql.NullBool    `json:"is_day"`
	Condition           string          `json:"condition"`
	Category            string          `json:"category"`
	Icon                string          `json:"icon"`
	WinddirIcon         string          `json:"winddir_icon"`
	WinddirText         string          `json:"winddir_text"`
	TempUnit            string          `json:"temp_unit"`
	WindspeedUnit       string          `json:"windspeed_unit"`
	HumidityUnit        string          `json:"humidity_unit"`
	PressureUnit        string          `json:"pressure_unit"`
	WinddirUnit         string          `json:"winddir_unit"`
	Timezone            string          `json:"timezone"`
	TimezoneAbbr        sql.NullString  `json:"timezone_abbr"`
	UpdatedAt           int64           `json:"updated_at_unix"`
}
