// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package model

type Location struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	Latitude  float64     `json:"latitude"`
	Longitude float64     `json:"longitude"`
	Altitude  interface{} `json:"altitude"`
	Accuracy  float64     `json:"accuracy"`
	UpdatedAt int64       `json:"updated_at"`
	CreatedAt int64       `json:"created_at"`
}
