// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package model

import (
	"context"
)

type Querier interface {
	AddressByCoords(ctx context.Context, arg AddressByCoordsParams) (Address, error)
	NewAddress(ctx context.Context, arg NewAddressParams) (Address, error)
}

var _ Querier = (*Queries)(nil)
