// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package model

import (
	"context"
)

type Querier interface {
	LocationByID(ctx context.Context, id int64) (Location, error)
}

var _ Querier = (*Queries)(nil)
