// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weather.sql

package model

import (
	"context"
)

const currentWeatherByAddressID = `-- name: CurrentWeatherByAddressID :one
SELECT address_id, timestamp, temperature, apparent_temperature, weather_code, wind_speed, wind_gusts, wind_direction, relative_humidity, pressure_msl, is_day, updated_at
FROM current_weather
WHERE address_id = ?
`

func (q *Queries) CurrentWeatherByAddressID(ctx context.Context, addressID int64) (CurrentWeather, error) {
	row := q.db.QueryRowContext(ctx, currentWeatherByAddressID, addressID)
	var i CurrentWeather
	err := row.Scan(
		&i.AddressID,
		&i.Timestamp,
		&i.Temperature,
		&i.ApparentTemperature,
		&i.WeatherCode,
		&i.WindSpeed,
		&i.WindGusts,
		&i.WindDirection,
		&i.RelativeHumidity,
		&i.PressureMsl,
		&i.IsDay,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCurrentWeather = `-- name: UpdateCurrentWeather :exec
INSERT INTO current_weather (address_id,
                             timestamp,
                             temperature,
                             apparent_temperature,
                             weather_code,
                             wind_speed,
                             wind_gusts,
                             wind_direction,
                             relative_humidity,
                             pressure_msl,
                             is_day,
                             updated_at)
VALUES (?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9,
        ?10,
        ?11,
        ?12)
ON CONFLICT (address_id) DO UPDATE SET timestamp            = excluded.timestamp,
                                       temperature          = excluded.temperature,
                                       apparent_temperature = excluded.apparent_temperature,
                                       weather_code         = excluded.weather_code,
                                       wind_speed           = excluded.wind_speed,
                                       wind_gusts           = excluded.wind_gusts,
                                       wind_direction       = excluded.wind_direction,
                                       relative_humidity    = excluded.relative_humidity,
                                       pressure_msl         = excluded.pressure_msl,
                                       is_day               = excluded.is_day,
                                       updated_at           = excluded.updated_at
WHERE excluded.timestamp > current_weather.timestamp
`

type UpdateCurrentWeatherParams struct {
	AddressID           int64
	Timestamp           int64
	Temperature         float64
	ApparentTemperature float64
	WeatherCode         int64
	WindSpeed           float64
	WindGusts           float64
	WindDirection       float64
	RelativeHumidity    float64
	PressureMsl         float64
	IsDay               bool
	UpdatedAt           int64
}

func (q *Queries) UpdateCurrentWeather(ctx context.Context, arg UpdateCurrentWeatherParams) error {
	_, err := q.db.ExecContext(ctx, updateCurrentWeather,
		arg.AddressID,
		arg.Timestamp,
		arg.Temperature,
		arg.ApparentTemperature,
		arg.WeatherCode,
		arg.WindSpeed,
		arg.WindGusts,
		arg.WindDirection,
		arg.RelativeHumidity,
		arg.PressureMsl,
		arg.IsDay,
		arg.UpdatedAt,
	)
	return err
}
