// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weather.sql

package model

import (
	"context"
	"database/sql"
)

const currentWeatherByAddressIDAndBaseUnit = `-- name: CurrentWeatherByAddressIDAndBaseUnit :one
SELECT address_id, timestamp, temperature, apparent_temperature, weather_code, wind_speed, wind_gusts, wind_direction, relative_humidity, pressure_msl, temp_day_min, temp_day_max, uv_index, is_day, sunrise_utc, sunset_utc, condition, category, icon, winddir_icon, winddir_text, temp_unit, windspeed_unit, humidity_unit, pressure_unit, winddir_unit, timezone, timezone_abbr, base_unit, updated_at, moonphase, moonphase_icon, moonphase_icon_url
FROM current_weather
WHERE address_id = ?
  AND base_unit = ?
`

type CurrentWeatherByAddressIDAndBaseUnitParams struct {
	AddressID int64  `json:"-"`
	BaseUnit  string `json:"base_unit"`
}

func (q *Queries) CurrentWeatherByAddressIDAndBaseUnit(ctx context.Context, arg CurrentWeatherByAddressIDAndBaseUnitParams) (CurrentWeather, error) {
	row := q.db.QueryRowContext(ctx, currentWeatherByAddressIDAndBaseUnit, arg.AddressID, arg.BaseUnit)
	var i CurrentWeather
	err := row.Scan(
		&i.AddressID,
		&i.Timestamp,
		&i.Temperature,
		&i.ApparentTemperature,
		&i.WeatherCode,
		&i.WindSpeed,
		&i.WindGusts,
		&i.WindDirection,
		&i.RelativeHumidity,
		&i.PressureMsl,
		&i.TempDayMin,
		&i.TempDayMax,
		&i.UvIndex,
		&i.IsDay,
		&i.SunriseUtc,
		&i.SunsetUtc,
		&i.Condition,
		&i.Category,
		&i.Icon,
		&i.WinddirIcon,
		&i.WinddirText,
		&i.TempUnit,
		&i.WindspeedUnit,
		&i.HumidityUnit,
		&i.PressureUnit,
		&i.WinddirUnit,
		&i.Timezone,
		&i.TimezoneAbbr,
		&i.BaseUnit,
		&i.UpdatedAt,
		&i.Moonphase,
		&i.MoonphaseIcon,
		&i.MoonphaseIconUrl,
	)
	return i, err
}

const updateCurrentWeather = `-- name: UpdateCurrentWeather :exec
INSERT INTO current_weather (address_id,
                             timestamp,
                             temperature,
                             apparent_temperature,
                             weather_code,
                             wind_speed,
                             wind_gusts,
                             wind_direction,
                             relative_humidity,
                             pressure_msl,
                             temp_day_min,
                             temp_day_max,
                             uv_index,
                             is_day,
                             sunrise_utc,
                             sunset_utc,
                             moonphase,
                             moonphase_icon,
                             moonphase_icon_url,
                             condition,
                             category,
                             icon,
                             winddir_icon,
                             winddir_text,
                             temp_unit,
                             windspeed_unit,
                             humidity_unit,
                             pressure_unit,
                             winddir_unit,
                             timezone,
                             timezone_abbr,
                             base_unit,
                             updated_at)
VALUES (?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9,
        ?10,
        ?11,
        ?12,
        ?13,
        ?14,
        ?15,
        ?16,
        ?17,
        ?18,
        ?19,
        ?20,
        ?21,
        ?22,
        ?23,
        ?24,
        ?25,
        ?26,
        ?27,
        ?28,
        ?29,
        ?30,
        ?31,
        ?32,
        ?33)
ON CONFLICT (address_id, base_unit) DO UPDATE SET timestamp            = excluded.timestamp,
                                                  temperature          = excluded.temperature,
                                                  apparent_temperature = excluded.apparent_temperature,
                                                  weather_code         = excluded.weather_code,
                                                  wind_speed           = excluded.wind_speed,
                                                  wind_gusts           = excluded.wind_gusts,
                                                  wind_direction       = excluded.wind_direction,
                                                  relative_humidity    = excluded.relative_humidity,
                                                  pressure_msl         = excluded.pressure_msl,
                                                  temp_day_min         = excluded.temp_day_min,
                                                  temp_day_max         = excluded.temp_day_max,
                                                  uv_index             = excluded.uv_index,
                                                  is_day               = excluded.is_day,
                                                  sunrise_utc          = excluded.sunrise_utc,
                                                  sunset_utc           = excluded.sunset_utc,
                                                  moonphase            = excluded.moonphase,
                                                  moonphase_icon       = excluded.moonphase_icon,
                                                  moonphase_icon_url   = excluded.moonphase_icon_url,
                                                  condition            = excluded.condition,
                                                  category             = excluded.category,
                                                  icon                 = excluded.icon,
                                                  winddir_icon         = excluded.winddir_icon,
                                                  winddir_text         = excluded.winddir_text,
                                                  temp_unit            = excluded.temp_unit,
                                                  windspeed_unit       = excluded.windspeed_unit,
                                                  humidity_unit        = excluded.humidity_unit,
                                                  pressure_unit        = excluded.pressure_unit,
                                                  winddir_unit         = excluded.winddir_unit,
                                                  timezone             = excluded.timezone,
                                                  timezone_abbr        = excluded.timezone_abbr,
                                                  base_unit            = excluded.base_unit,
                                                  updated_at           = excluded.updated_at
WHERE excluded.timestamp > current_weather.timestamp
`

type UpdateCurrentWeatherParams struct {
	AddressID           int64           `json:"-"`
	Timestamp           sql.NullInt64   `json:"timestamp_unix"`
	Temperature         sql.NullFloat64 `json:"temperature"`
	ApparentTemperature sql.NullFloat64 `json:"apparent_temperature"`
	WeatherCode         sql.NullInt64   `json:"weather_code"`
	WindSpeed           sql.NullFloat64 `json:"wind_speed"`
	WindGusts           sql.NullFloat64 `json:"wind_gusts"`
	WindDirection       sql.NullFloat64 `json:"wind_direction"`
	RelativeHumidity    sql.NullFloat64 `json:"relative_humidity"`
	PressureMsl         sql.NullFloat64 `json:"pressure_msl"`
	TempDayMin          sql.NullFloat64 `json:"temp_day_min"`
	TempDayMax          sql.NullFloat64 `json:"temp_day_max"`
	UvIndex             sql.NullFloat64 `json:"uv_index"`
	IsDay               sql.NullBool    `json:"is_day"`
	SunriseUtc          int64           `json:"sunrise_utc"`
	SunsetUtc           int64           `json:"sunset_utc"`
	Moonphase           sql.NullString  `json:"moonphase"`
	MoonphaseIcon       sql.NullString  `json:"moonphase_icon"`
	MoonphaseIconUrl    sql.NullString  `json:"moonphase_icon_url"`
	Condition           string          `json:"condition"`
	Category            string          `json:"category"`
	Icon                string          `json:"icon"`
	WinddirIcon         string          `json:"winddir_icon"`
	WinddirText         string          `json:"winddir_text"`
	TempUnit            string          `json:"temp_unit"`
	WindspeedUnit       string          `json:"windspeed_unit"`
	HumidityUnit        string          `json:"humidity_unit"`
	PressureUnit        string          `json:"pressure_unit"`
	WinddirUnit         string          `json:"winddir_unit"`
	Timezone            string          `json:"timezone"`
	TimezoneAbbr        sql.NullString  `json:"timezone_abbr"`
	BaseUnit            string          `json:"base_unit"`
	UpdatedAt           int64           `json:"updated_at_unix"`
}

func (q *Queries) UpdateCurrentWeather(ctx context.Context, arg UpdateCurrentWeatherParams) error {
	_, err := q.db.ExecContext(ctx, updateCurrentWeather,
		arg.AddressID,
		arg.Timestamp,
		arg.Temperature,
		arg.ApparentTemperature,
		arg.WeatherCode,
		arg.WindSpeed,
		arg.WindGusts,
		arg.WindDirection,
		arg.RelativeHumidity,
		arg.PressureMsl,
		arg.TempDayMin,
		arg.TempDayMax,
		arg.UvIndex,
		arg.IsDay,
		arg.SunriseUtc,
		arg.SunsetUtc,
		arg.Moonphase,
		arg.MoonphaseIcon,
		arg.MoonphaseIconUrl,
		arg.Condition,
		arg.Category,
		arg.Icon,
		arg.WinddirIcon,
		arg.WinddirText,
		arg.TempUnit,
		arg.WindspeedUnit,
		arg.HumidityUnit,
		arg.PressureUnit,
		arg.WinddirUnit,
		arg.Timezone,
		arg.TimezoneAbbr,
		arg.BaseUnit,
		arg.UpdatedAt,
	)
	return err
}
